**NUMPY**

In [1]:
import numpy as np

In [2]:
myarr=np.array([[16,45,24,47]],np.int8)

In [3]:
myarr

array([[16, 45, 24, 47]], dtype=int8)

In [4]:
myarr[0,2]

24

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int8')

In [7]:
myarr[0,2]=100

In [8]:
myarr

array([[ 16,  45, 100,  47]], dtype=int8)

**Array Creation**

In [9]:
listarray=np.array([[2,4,9],[9,8,0],[8,5,6],[5,6,3]])

In [10]:
listarray

array([[2, 4, 9],
       [9, 8, 0],
       [8, 5, 6],
       [5, 6, 3]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(4, 3)

In [13]:
listarray.size

12

In [14]:
np.array({45,45,67})

array({67, 45}, dtype=object)

In [15]:
zeros=np.zeros((3,4))

In [16]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
rng=np.arange(11)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
lspace=np.linspace(1,50,10)

In [21]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [22]:
emp=np.empty((4,5))

In [23]:
emp

array([[2.84356555e-312, 0.00000000e+000, 8.76794447e+252,
        1.94918846e-153, 6.37112979e-067],
       [4.17576073e-057, 2.10856263e-052, 2.59027896e-144,
        6.18620730e+223, 4.90922082e+252],
       [8.03704416e-095, 3.94356143e+180, 9.60259819e-071,
        9.14796440e-071, 1.28255083e+160],
       [2.98831864e-032, 9.84316990e-072, 3.99910946e+252,
        3.19854319e+209, 1.58268989e-319]])

In [24]:
emp_like=np.empty_like((lspace))

In [25]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
ide=np.identity((20))

In [27]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [28]:
ide.shape

(20, 20)

In [29]:
arr=np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr=arr.reshape(3,33)

In [32]:
arr.shape

(3, 33)

In [33]:
arr=arr.ravel()

In [34]:
arr.shape

(99,)

In [35]:
x=[[4,5,6],
   [2,6,3],[8,6,6]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[4, 5, 6],
       [2, 6, 3],
       [8, 6, 6]])

In [38]:
ar.sum(axis=0)

array([14, 17, 15])

In [39]:
ar.sum(axis=1)

array([15, 11, 20])

In [40]:
ar.T

array([[4, 2, 8],
       [5, 6, 6],
       [6, 3, 6]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)


4
5
6
2
6
3
8
6
6


In [43]:
ar.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

In [46]:
one=np.array([1,56,4,3])

In [47]:
one

array([ 1, 56,  4,  3])

In [48]:
one.argmax()

1

In [49]:
one.argmin()

0

In [50]:
one.argsort()

array([0, 3, 2, 1], dtype=int32)

In [51]:
ar


array([[4, 5, 6],
       [2, 6, 3],
       [8, 6, 6]])

In [52]:
ar.argmax()

6

In [53]:
ar.argmin()

3

In [54]:
ar.argmax(axis=1)

array([2, 1, 0], dtype=int32)

In [55]:
ar.argmin(axis=1)

array([0, 0, 1], dtype=int32)

In [56]:
ar.argmax(axis=0)

array([2, 1, 0], dtype=int32)

In [57]:
ar

array([[4, 5, 6],
       [2, 6, 3],
       [8, 6, 6]])

In [58]:
ar2=np.array([[40, 50, 60],
       [20, 60, 30],
       [80, 60, 60]])

In [59]:
ar+ar2

array([[44, 55, 66],
       [22, 66, 33],
       [88, 66, 66]])

In [60]:
ar-ar2

array([[-36, -45, -54],
       [-18, -54, -27],
       [-72, -54, -54]])

In [61]:
ar*ar2

array([[160, 250, 360],
       [ 40, 360,  90],
       [640, 360, 360]])

In [62]:
np.sqrt(ar)

array([[2.        , 2.23606798, 2.44948974],
       [1.41421356, 2.44948974, 1.73205081],
       [2.82842712, 2.44948974, 2.44948974]])

In [63]:
ar.sum()

46

In [64]:
ar.max()

8

In [65]:
ar.min()

2

In [66]:
ar

array([[4, 5, 6],
       [2, 6, 3],
       [8, 6, 6]])

In [67]:
np.count_nonzero(ar)

9

In [68]:
np.where(ar>5)

(array([0, 1, 2, 2, 2], dtype=int32), array([2, 1, 0, 1, 2], dtype=int32))

In [69]:
type(np.where(ar>5))

tuple

In [70]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32))

In [71]:
ar[1,2]=0

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int32))

In [73]:
import sys

In [74]:
py_ar=[4,65,21,9]

In [75]:
np_ar=np.array(py_ar)

In [76]:
sys.getsizeof(1)*len(py_ar)

56

In [77]:
np_ar.itemsize*np_ar.size

16

In [78]:
np_ar.tolist()

[4, 65, 21, 9]